spring.application.name=routemaker_backend

# 데이터베이스 연결 설정 (Docker로 띄운 포트와 계정 정보)
spring.datasource.url=jdbc:postgresql://localhost:5432/study_db
spring.datasource.username=study_user
spring.datasource.password=study_password
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA 설정 (테이블 자동 생성 및 SQL 로그 보기)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true