spring.application.name=routemaker_backend

# 1. PostgreSQL 연결 설정
spring.datasource.url=jdbc:postgresql://localhost:5432/routemaker_db
spring.datasource.username=user
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. Redis 캐시 서버 연결 설정
spring.data.redis.host=localhost
spring.data.redis.port=6379

# 3. JPA/Hibernate 설정- 테이블 자동생성
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true